param([string]$ProfileRoot)

$script:ModuleRoot = Split-Path $PSScriptRoot -Parent | Split-Path -Parent
$script:GeneratedDir = Join-Path $script:ModuleRoot "generated"
$script:ManifestPath = Join-Path $script:GeneratedDir "manifest.json"

# ── Auto-generate if needed ───────────────────────────────────────────────────
function Invoke-StarshipAutoBuild {
    $generatePy = Join-Path $script:ModuleRoot "generate.py"
    if (-not (Test-Path $generatePy)) {
        Write-Warning "starshipauto: generate.py not found at $generatePy"
        return $false
    }
    $result = & python $generatePy 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "starshipauto: generate.py failed: $result"
        return $false
    }
    $result | ForEach-Object { Write-Host $_ -ForegroundColor DarkGray }
    return $true
}

function Test-StarshipAutoGenerated {
    if (-not (Test-Path $script:ManifestPath)) { return $false }
    $tomlFiles = Get-ChildItem (Join-Path $script:GeneratedDir "*.toml") -ErrorAction SilentlyContinue
    return ($null -ne $tomlFiles -and $tomlFiles.Count -gt 0)
}

if (-not (Test-StarshipAutoGenerated)) {
    Invoke-StarshipAutoBuild | Out-Null
}

# ── Manifest access ──────────────────────────────────────────────────────────
function Get-StarshipAutoManifest {
    if (-not (Test-Path $script:ManifestPath)) { return $null }
    Get-Content $script:ManifestPath -Raw | ConvertFrom-Json
}

function Get-StarshipAutoConfigs {
    $manifest = Get-StarshipAutoManifest
    if (-not $manifest) { return @{} }
    $configs = @{}
    foreach ($cfg in $manifest.configs) {
        $configs[$cfg.name] = Join-Path $script:GeneratedDir $cfg.file
    }
    return $configs
}

function Get-StarshipAutoGeneratedDir {
    return $script:GeneratedDir
}

# ── Query functions ───────────────────────────────────────────────────────────
function Get-StarshipLayout {
    $layoutDir = Join-Path $script:ModuleRoot "data\layouts"
    Get-ChildItem "$layoutDir\*.toml" | ForEach-Object { $_.BaseName }
}

function Get-StarshipPalette {
    param([string]$Layout)
    $paletteDir = Join-Path $script:ModuleRoot "data\palettes"
    Get-ChildItem "$paletteDir\*.toml" | ForEach-Object { $_.BaseName }
}

Export-ModuleMember -Function @(
    'Invoke-StarshipAutoBuild'
    'Test-StarshipAutoGenerated'
    'Get-StarshipAutoManifest'
    'Get-StarshipAutoConfigs'
    'Get-StarshipAutoGeneratedDir'
    'Get-StarshipLayout'
    'Get-StarshipPalette'
)
